openapi: 3.0.0
servers:
  - description: Dev server
    url: http://localhost:5555
  - description: Prod server
    url: http://localhost:5555
info:
  version: "1.0.0"
  title: Client project API Documentation
tags:
  - name: Auth
    description: Authentificate user
paths:
  /login:
    post:
      tags:
        - Auth
      summary: authorize user
      requestBody:
        content:
          application/json:
            schema:
              type: object
              required:
                - email
                - password
              properties:
                email:
                  description: user email
                  type: string
                password:
                  description: user password
                  type: string
      responses:
        '200':
          description: OK
        '401':
          description: Not Authorized
  /gallery:
    get:
      tags:
        - Gallery
      summary: gallery with query page parameters
      parameters:
        - name: authorization
          in: header
          schema:
            type: string
          example: token
        - name: page
          in: query
          schema:
            type: integer
          example: '2'
      responses:
        '200':
          description: Successful response
        '401':
          description: Not Authorized
    post:
      tags:
        - Gallery
      summary: upload picture to the server
      requestBody:
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                picture:
                  type: string
                  format: binary
      parameters:
        - name: authorization
          in: header
          schema:
            type: string
          example: token
      responses:
        '201':
          description: Created
        '400':
          description: Bad Request
